import React from 'react'

export default function Staticwebapps() {
    return (<>
      
            <h2 className="text-center pb-3">We provide STATIC Web Application Production service </h2>

            <p>
            A static web page is a web page that is delivered to the user's web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.
            A static website contains Web pages with fixed content. Each page is coded in HTML and displays the same information to every visitor. Static sites are the most basic type of website and are the easiest to create. Unlike dynamic websites, they do not require any Web programming or database design.
            </p>

            <img src="https://coder.today/tech/2018-10-27_10-examples-of-how-to-use-static-html-websites/images/1.png" className="w-100" />

            <ul>
                <li>Interaction Design</li>
                <li>Wireframes</li>
                <li>Prototypes</li>
                <li>User Research</li>
                <li>Visual Design</li>
                <li>Layouts</li>
                <li>Typography</li>
                <li>Colors</li>
                <li>Graphic Design</li>
            </ul>

    
    </>)
}